---
shared:
  image: node:16
  environment:
    SD_TEMPLATE_PATH: ./template.yaml
jobs:
  validate_template:
    requires: [~pr, ~commit]
    steps:
      - echo_SD_TEMPLATE_PATH: echo $SD_TEMPLATE_PATH
      - install_prerequisites: npm install -g screwdriver-template-main
      - validate_template: template-validate

  publish_template:
    requires: [validate_template]
    steps:
      - install_prerequisites: npm install -g screwdriver-template-main
      - publish: template-publish
      - autotag: template-tag --name amitlata/screwdriver --tag latest
